### ISSUE TITLE
Installation test failure

### ISSUE THREAD

**Issue by gokul-0205** [materialsinnovation/pymks#523] opened 2020-09-18 02:13 UTC
I tried to install pymks in my windows conda environment.
I followed the steps as given in github.

But while running the command 
`python -c "import pymks; pymks.test()"`
I am getting the following errors.

![Capture](https://user-images.githubusercontent.com/71476493/93547337-b1c1fb00-f919-11ea-85ad-78c8fb1840a4.PNG)
![Capture1](https://user-images.githubusercontent.com/71476493/93547343-b71f4580-f919-11ea-93ce-7e0068b6bed5.PNG)
![Capture2](https://user-images.githubusercontent.com/71476493/93547349-ba1a3600-f919-11ea-8232-3e009f0274a6.PNG)

Can someone please help me resolve the issue?

**Comment by wd15** [comment] 2020-09-18 13:59
Hi @gokul-0205, thanks for reporting this. It really helps. The good thing is that these test errors are likely not important. I think you can go ahead and use PyMKS without worrying. It's reporting an "int32" rather than an "int64" as the type for some Dask arrays.

I'll keep this issue open so that I rework the tests to avoid this type of error in future.

**Comment by wd15** [comment] 2021-03-05 21:47
I can't reproduce this issue so closing. Please reopen if you're still experiencing these test failures.

**Closed by wd15** 2021-03-05 21:47 UTC
Labels: bug
