### ISSUE TITLE
nix- build failing due to dask-glm

### ISSUE THREAD

**Issue by auag92** [materialsinnovation/pymks#371] opened 2019-03-26 13:43 UTC
nix build failing with the following error. 
 - because dask-glm build is failing.
https://pypi.org/project/dask-glm/

![dask-glm-fail](https://user-images.githubusercontent.com/10386906/55001705-99368600-4fab-11e9-8b4a-367508c65c83.png)

**Comment by wd15** [comment] 2019-05-17 18:35
This was really strange since one would image that Nix is entirely reproducible. The error is to do with setuptools_scm not being available, but surely that would have failed on Travis CI  last year when we were developing the Nix expression. Anyway, setuptools_scm is now a dependency for dask-glm and this is issue is now fixed with #385

**Closed by wd15** 2019-05-17 18:35 UTC
